services:
  hostap:
    image: ghcr.io/unspezifisch/iot-hostap
    build:
      context: .
    deploy:
      resources:
        limits:
          memory: 100M
    privileged: true
    network_mode: host
    tty: true
    environment:
      INTERFACE: wlan0
      CHANNEL: 6
      SSID: iot
      AP_ADDR: 192.168.254.1
      WPA_PASSPHRASE: passw0rd
      COUNTRY_CODE: EU
      HT_ENABLED: 1
    restart: unless-stopped

