services:
  hostap:
    image: ghcr.io/unspezifisch/iot-hostap
    build:
      context: .
    deploy:
      resources:
        limits:
          memory: 100M
    network_mode: host
    # caps/devices needed for hostapd
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/rfkill
    environment:
      INTERFACE: wlan0
      CHANNEL: 6
      SSID: iot
      AP_ADDR: 192.168.254.1
      WPA_PASSPHRASE: passw0rd
      COUNTRY_CODE: EU
      HT_ENABLED: 1
    restart: unless-stopped

